subjects = ["C", "Java", "Javascript", "Python"]
print(subjects)
print(subjects[0:])
print(subjects[0])
print(subjects[2:])
print(subjects[-1])
print("Python" in subjects)
print("Swwift" in subjects)
print("Swwift" not in subjects)
print(subjects + ["Swift", 24])
print(len(subjects))
subjects.append("C++")
print(subjects)
subjects.insert(2,"OS")
print(subjects)
subjects.remove("OS")
print(subjects)
